### ISSUE TITLE
Feature roadmap

### ISSUE THREAD

**Issue by cdvv7788** [gurleensethi/http_middleware#3]
What plans do you have with the package? Are there missing features or will you focus on ironing the current ones?

**Comment by gurleensethi** [comment]
This library is supposed to be an abstraction on top oh `http` so developers can built packages for the abstraction. Right now I don't have any plans for adding any new major features, although I am open for new ideas, suggestions and collaborations! 
So if you have something in mind, do share it!

**Comment by cdvv7788** [comment]
Got it. I will if something comes to mind.

**Comment by gurleensethi** [comment]
You are open to build packages on top of this lib, it would mean a lot :)
